version: '3.4'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    restart: on-failure
    ports:
      - "9200:9200"
    volumes:
      - ./target/releases/elasticsearch-analysis-vietnamese-${ES_VERSION}.zip:/usr/share/elasticsearch/plugin/elasticsearch-analysis-vietnamese-${ES_VERSION}.zip
      - ./install-es-plugin.sh:/apps/install-es-plugin.sh
    environment:
      - "ES_VERSION=${ES_VERSION}"
      - "discovery.type=single-node"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    entrypoint:
      - /apps/install-es-plugin.sh

  kibana:
    image: docker.elastic.co/kibana/kibana:${ES_VERSION}
    ports:
      - "5601:5601"

